apiVersion: v1
kind: ServiceAccount
metadata:
  name: dist-exec-master
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dist-exec-scaler
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dist-exec-master-scaler
  namespace: default
subjects:
  - kind: ServiceAccount
    name: dist-exec-master
roleRef:
  kind: Role
  name: dist-exec-scaler
  apiGroup: rbac.authorization.k8s.io
