apiVersion: v1
kind: Service
metadata:
  name: dist-exec-master
  namespace: default
  labels:
    app: dist-exec-master
spec:
  type: ClusterIP
  selector:
    app: dist-exec-master
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
