apiVersion: v1
kind: Service
metadata:
  name: dist-exec-workers
  namespace: default
  labels:
    app: dist-exec-worker
spec:
  clusterIP: None  # Headless service
  selector:
    app: dist-exec-worker
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
